apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webapp-server
  template:
    metadata:
      labels:
        app: webapp-server
    spec:
      containers:
      - name: webapp
        image: aspnetmonitoring
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 250m
            memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-server
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/port:   '80'
spec:
  type: LoadBalancer
  ports:
  - port: 5000
    targetPort: 80
  selector:
    app: webapp-server